// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh282gwjtmR0pZsK8TfJ4S0tZ3fqGgHhE',
    appId: '1:582601284988:web:6af8180acca617a6fc58f9',
    messagingSenderId: '582601284988',
    projectId: 'atelier-4-elghoul-iir5g6',
    authDomain: 'atelier-4-elghoul-iir5g6.firebaseapp.com',
    storageBucket: 'atelier-4-elghoul-iir5g6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTeeCGlNLTKaIsi2R1nHXCmyVijf5-4CU',
    appId: '1:582601284988:android:e01b2f6b51f3ee8dfc58f9',
    messagingSenderId: '582601284988',
    projectId: 'atelier-4-elghoul-iir5g6',
    storageBucket: 'atelier-4-elghoul-iir5g6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9ejQtQ0puSOaeQWPpdfouEOvp7qNsAa8',
    appId: '1:582601284988:ios:dde0adf351ece846fc58f9',
    messagingSenderId: '582601284988',
    projectId: 'atelier-4-elghoul-iir5g6',
    storageBucket: 'atelier-4-elghoul-iir5g6.firebasestorage.app',
    iosBundleId: 'com.example.restaubook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9ejQtQ0puSOaeQWPpdfouEOvp7qNsAa8',
    appId: '1:582601284988:ios:dde0adf351ece846fc58f9',
    messagingSenderId: '582601284988',
    projectId: 'atelier-4-elghoul-iir5g6',
    storageBucket: 'atelier-4-elghoul-iir5g6.firebasestorage.app',
    iosBundleId: 'com.example.restaubook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh282gwjtmR0pZsK8TfJ4S0tZ3fqGgHhE',
    appId: '1:582601284988:web:658876f3b1affffefc58f9',
    messagingSenderId: '582601284988',
    projectId: 'atelier-4-elghoul-iir5g6',
    authDomain: 'atelier-4-elghoul-iir5g6.firebaseapp.com',
    storageBucket: 'atelier-4-elghoul-iir5g6.firebasestorage.app',
  );

}