// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXtyVctpHy0QjK9ux5WOj3R0ApScpvuVc',
    appId: '1:322403667686:web:8a5858cc12c041b86d7527',
    messagingSenderId: '322403667686',
    projectId: 'restaubook-89fa3',
    authDomain: 'restaubook-89fa3.firebaseapp.com',
    storageBucket: 'restaubook-89fa3.firebasestorage.app',
    measurementId: 'G-G96S1EZH06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLUvm2K47C5Surmv5Np8_LT5y9dTvEU5A',
    appId: '1:322403667686:android:97f2910fdc6fe1156d7527',
    messagingSenderId: '322403667686',
    projectId: 'restaubook-89fa3',
    storageBucket: 'restaubook-89fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqpBNtPerSCETLI1PS0SbRPmS3fjqYg5c',
    appId: '1:322403667686:ios:44864438e80e08056d7527',
    messagingSenderId: '322403667686',
    projectId: 'restaubook-89fa3',
    storageBucket: 'restaubook-89fa3.firebasestorage.app',
    iosBundleId: 'com.example.restaubook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqpBNtPerSCETLI1PS0SbRPmS3fjqYg5c',
    appId: '1:322403667686:ios:44864438e80e08056d7527',
    messagingSenderId: '322403667686',
    projectId: 'restaubook-89fa3',
    storageBucket: 'restaubook-89fa3.firebasestorage.app',
    iosBundleId: 'com.example.restaubook',
  );
}
